### PR TITLE
Using poise-python cookbook in place of python cookbook

### PR DESCRIPTION
**Pull request by nilroy**
Replacing python cookbook as it is deprecated

### CODE REVIEW

**Comment by nilroy** [comment]
@JonathanTron Please review

**Comment by nilroy** [comment]
@JonathanTron I could not make sentry working using the runit (defined in the _service recipie). I am using wrapper cookbook that uses supervisor for doing the same purpose. I shall create a separate PR and make provsion so that people can choose between supervisor and runit

**Comment by klyonrad** [comment]
Could you please also increase the version in the `metadata.rb` ?

**Comment by JonathanTron** [comment]
Hi @klyonrad, done!

**Comment by klyonrad** [comment]
Thanks for the quick fix!
(I'm currently writing a wrapper cookbook too with the same issue als @nilroy )

**Pull request merged**
