### PR TITLE
Support for sentry 8

### PR DESCRIPTION
**Pull request by nilroy**
Changes required for supporting sentry 8.x

### CODE REVIEW

**Comment by JonathanTron** [comment]
Thanks a lot for your work on this!

**Comment by nilroy** [comment]
@JonathanTron Thanks for merging the PR. Is it possible to add me to contributor list for this project? Also have you thought of hosting it in chef supermarket? I am not very familiar with the process though.

**Comment by JonathanTron** [comment]
@nilroy You're welcome, thanks for your work on this! 

You're now collaborator on the project, so you have push rights.

As for supermarket, yes I've pushed some other cookbook on it, I'm short in time currently, but I will try to push it soon.

**Comment by JonathanTron** [comment]
@nilroy If you give me your username on Supermarket I can make you collaborator on it too, so that you will be able to push new release.

**Comment by nilroy** [comment]
@JonathanTron  Thanks a lot. My supermarket username is nilanjan1

**Comment by JonathanTron** [comment]
@nilroy Done!

**Pull request merged**
