### PR TITLE
Fixed the GITHUB _API_SECRET parameter

### PR DESCRIPTION
**Pull request by nilroy**

### CODE REVIEW

**Comment by nilroy** [comment]
@JonathanTron request review

**Comment by JonathanTron** [comment]
Thanks for catching it!

**Comment by nilroy** [comment]
@JonathanTron can we have a new release for it? The 0.4.4 is unusable without it

**Comment by JonathanTron** [comment]
Yes I'll release it later today.

**Comment by JonathanTron** [comment]
@nilroy v0.4.5 released to supermarket with your PRs : https://supermarket.chef.io/cookbooks/sentry

Thanks again!

**Pull request merged**
